package store

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base32"
	"errors"
	"fmt"
	"os"
	"slices"
	"strings"
	"sync"
	"time"
)

// SubscribersFile holds the panel's own subscribers. Written *only* by the daemon.
const SubscribersFile = "subscribers.json"

// ErrReadOnly is what a mutator returns when this process is not the daemon.
//
// The daemon is the only writer of subscribers.json, and unlike admins.json that cannot
// be left to convention. The daemon keeps the whole list in memory and rewrites the file
// wholesale, so a CLI write would be silently undone by the panel's next edit — and a
// future `vlessvmorectl subscribers rm`, written without noticing, would corrupt data
// while passing its own tests. Making the CLI's handle structurally read-only means that
// command fails on its first run instead.
var ErrReadOnly = errors.New("subscribers.json is written only by the running panel")

// MaxEntriesPerSubscriber caps how many accounts one share link may aggregate.
//
// This is not a UI concern, which is why it lives here. The entry count is the fan-out
// factor of an unauthenticated endpoint: one GET of a share link becomes roughly two
// credentialed calls per entry against nodes that are, by design, small. The cap is what
// turns "unbounded" into a number.
const MaxEntriesPerSubscriber = 32

// crockford is the sibling project's alphabet, which omits I, L, O and U so a token
// cannot be misread between similar glyphs or accidentally spell a word.
//
// Matching the node's encoding is not cosmetic. An operator ends up holding two kinds of
// capability URL for the same person — https://vpn.example.com/sub/QK7M2X… from the node
// and https://panel.example.com/access/… from here — and having them look like the same
// class of object is how they come to be handled with the same care.
var crockford = base32.NewEncoding("0123456789ABCDEFGHJKMNPQRSTVWXYZ").WithPadding(base32.NoPadding)

const (
	// shareTokenBytes is 160 bits, the same width the sibling uses for /sub/{token} and
	// for the same argument: the URL *is* the credential, so it has to be unguessable
	// standing alone, with no rate limit anywhere in the world able to save it.
	// 20 bytes encodes to exactly 32 characters.
	shareTokenBytes = 20

	// minShareTokenLen is what load enforces, rather than an exact length. The check
	// exists to catch `"token": "test"` in a hand-edited file — a four-character share
	// link, live and brute-forceable — not to freeze the width forever. 26 characters
	// is 130 bits.
	minShareTokenLen = 26
	maxShareTokenLen = 64

	// idBytes is 40 bits, which is 8 base32 characters.
	//
	// Deliberately much shorter than a token, and lowercase, because the two are not the
	// same kind of thing. A token has to survive brute force; an id only has to be
	// unique among a handful of records, and it is read, typed and pasted by an operator
	// — so it is sized for the eye rather than for an attacker. Collisions are handled by
	// retrying against the index rather than by adding width.
	idBytes = 5

	maxSubscriberNameLen = 128
	maxSubscriberNoteLen = 4096
	maxEntryLabelLen     = 128
	maxVlessUserIDLen    = 128
)

// Subscriber is a real person who holds VPN accounts on one or more managed nodes.
//
// This is the first thing the panel owns that is not "who may log in", so it is worth
// being precise about what it is not: it is not a mirror. Every field here is either
// generated by this program or typed by an operator into this program. The accounts
// themselves stay where they are — an Entry is a *reference*, two opaque strings — and
// the node remains the only place that knows whether that account exists, is enabled, or
// has any traffic left. See the package doc.
type Subscriber struct {
	// ID is what the panel's own routes and the operator's UI key on. Random rather
	// than derived: a subscriber has no natural key (two people are called Ivan), and a
	// name-derived id would change under a rename and break every bookmark.
	//
	// It stays a separate value from Token even though neither ever changes, because
	// they have opposite handling rules: an ID is safe in the operator's URL bar,
	// browser history and screen recordings, and a Token is not.
	ID string `json:"id"`

	// Name is the operator's label for the person, and the one identifying thing on the
	// public page — a page that opens with the reader's own name is how they know the
	// link is the one meant for them and not a mis-paste.
	Name string `json:"name"`

	// Note is the operator's private scratch space: "paid to August", "brother of the
	// other Ivan". It is deliberately absent from the public projection. If it ever
	// appears there, somebody's billing state is readable by whoever they forwarded the
	// link to.
	Note string `json:"note,omitempty"`

	// Token is the share secret, stored in the clear and minted exactly once.
	//
	// A deliberate departure from sessions.json, which stores only hashes, and the two
	// differ for the reason each exists. A session cookie is minted for one browser and
	// never read back, so hashing it costs nothing. This token is a capability meant to
	// be re-shared: the operator has to be able to reopen the panel in October and copy
	// the link again for somebody who lost it. A hash cannot do that.
	//
	// What makes it acceptable is that it is not an escalation. Everything it unlocks is
	// a set of node sub_tokens, which are themselves plaintext capability URLs already
	// sitting in that person's VPN client; this aggregates them and adds usage figures,
	// it does not outrank them. It never appears in a log (see api.redactPath), never in
	// the public projection, and the file is mode 0600.
	//
	// There is no rotation. Revoking a leaked link means Disabled, or deleting the
	// record and building a new one.
	Token string `json:"token"`

	// Disabled is the operator's pause switch, and — with no rotation — the revocation
	// mechanism. It stops the share link answering without touching any node, any uuid,
	// or any subscription URL, so nobody is disconnected by it.
	//
	// Spelled negatively so that the zero value is *active*. A hand-added record with no
	// "enabled" key silently having no access is a 3am support call; a hand-added record
	// being active is what the person who typed it meant. "Fail closed" has no threat
	// model here — anyone who can write this file can also write `false`.
	Disabled bool `json:"disabled,omitempty"`

	Entries []SubscriberEntry `json:"entries"`

	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// SubscriberEntry attaches one node account to a subscriber.
type SubscriberEntry struct {
	// ID is the panel's handle for this attachment. It exists so DELETE has something to
	// name, and so the public page has a stable list key that is not the node's user id
	// — that page must be able to identify an entry without disclosing which node it
	// lives on.
	ID string `json:"id"`

	// ServerID is config.Server.ID, the twelve hex characters derived from the node's
	// origin. Not the URL: the URL is environment.
	//
	// Deriving it from the origin is not free — changing a node's address changes its id
	// and orphans every entry pointing at it. The difference is that they orphan
	// visibly, resolving to "this node is no longer configured" at render time, rather
	// than pointing at a URL the panel no longer manages.
	ServerID string `json:"server_id"`

	// VlessUserID is the node's internal user id, e.g. "u_0B4X6TWQ8ZKM3N1PVJHR5DGYAC".
	//
	// The node's API also accepts a display name in that position, and it must not be
	// used here: names are mutable, so a rename on the node would silently re-point this
	// entry at a different person's credentials, or at nothing.
	//
	// The shape is not validated beyond "printable, no slash". Requiring the "u_" prefix
	// would couple this file to the sibling's id format; the cost of accepting an odd
	// id is a dangling reference we already tolerate, while the cost of rejecting a
	// valid one is an operator who cannot attach an account.
	VlessUserID string `json:"vless_user_id"`

	// Label is the operator's own words for this account — "phone", "the laptop".
	// Panel-owned, and safe precisely because nothing on the node can make it wrong. The
	// node's live name is fetched at render time and shown alongside it.
	Label string `json:"label,omitempty"`

	AddedAt time.Time `json:"added_at"`
}

func (s Subscriber) clone() Subscriber {
	s.Entries = slices.Clone(s.Entries)
	return s
}

type subscribersDoc struct {
	Version     int          `json:"version"`
	Subscribers []Subscriber `json:"subscribers"`
}

// SubscriberUpdate is a patch. A nil pointer means "unchanged", which is what lets
// {"note":""} clear a note and {} change nothing. A struct of plain values could not
// express the difference.
type SubscriberUpdate struct {
	Name     *string
	Note     *string
	Disabled *bool
}

// NewEntry is the input to Attach.
type NewEntry struct {
	ServerID    string
	VlessUserID string
	Label       string
}

// Subscribers is the JSON-backed subscriber list.
type Subscribers struct {
	path     string
	writable bool

	mu   sync.RWMutex
	list []Subscriber

	// byID and byToken are rebuilt wholesale by reindexLocked after every mutation.
	//
	// Two maps rather than a scan, and rebuilt rather than patched, because a
	// partially-updated index here means one person's link resolving to another person's
	// accounts — the single worst thing this file can do.
	byID    map[string]int
	byToken map[[32]byte]string

	loadedSize    int64
	loadedModTime time.Time
}

// OpenSubscribers loads subscribers.json, treating a missing file as an empty list.
//
// A corrupt or wrong-version file is fatal, and the argument is stronger here than it is
// for admins.json. A lenient load — "treat a corrupt file as empty" — would be followed,
// the first time an operator creates a subscriber, by a whole-file rewrite, and the
// corrupt-but-recoverable file would be gone. Refusing to start is the only policy under
// which the operator still gets to fix it with a text editor.
func OpenSubscribers(path string, writable bool) (*Subscribers, error) {
	s := &Subscribers{path: path, writable: writable}
	if err := s.load(); err != nil {
		return nil, err
	}
	return s, nil
}

// load reads and validates the whole file before swapping it in, so a bad file never
// half-applies. Caller must not hold the lock.
func (s *Subscribers) load() error {
	var doc subscribersDoc
	found, err := readJSON(s.path, &doc)
	if err != nil {
		return err
	}
	if found && doc.Version != jsonVersion {
		return fmt.Errorf("%s: unsupported version %d, this build understands %d", s.path, doc.Version, jsonVersion)
	}

	seenID := make(map[string]bool, len(doc.Subscribers))
	seenToken := make(map[string]bool, len(doc.Subscribers))
	for i, sub := range doc.Subscribers {
		where := fmt.Sprintf("%s: subscribers[%d]", s.path, i)

		if strings.TrimSpace(sub.ID) == "" {
			return fmt.Errorf("%s: id is empty", where)
		}
		if seenID[sub.ID] {
			return fmt.Errorf("%s: duplicate id %q", where, sub.ID)
		}
		seenID[sub.ID] = true

		if err := validateSubscriberName(sub.Name); err != nil {
			return fmt.Errorf("%s: %w", where, err)
		}
		if len(sub.Note) > maxSubscriberNoteLen {
			return fmt.Errorf("%s: note is longer than %d characters", where, maxSubscriberNoteLen)
		}

		token := strings.ToUpper(sub.Token)
		if err := validateShareToken(token); err != nil {
			return fmt.Errorf("%s (%s): %w", where, sub.Name, err)
		}
		// The check this file exists for. Two records sharing a token is one link
		// resolving to two people's accounts.
		if seenToken[token] {
			return fmt.Errorf("%s (%s): its token is already used by another subscriber", where, sub.Name)
		}
		seenToken[token] = true

		if len(sub.Entries) > MaxEntriesPerSubscriber {
			return fmt.Errorf("%s (%s): has %d entries, more than the maximum of %d",
				where, sub.Name, len(sub.Entries), MaxEntriesPerSubscriber)
		}
		seenEntry := make(map[string]bool, len(sub.Entries))
		seenPair := make(map[string]bool, len(sub.Entries))
		for j, e := range sub.Entries {
			ewhere := fmt.Sprintf("%s (%s): entries[%d]", where, sub.Name, j)
			if strings.TrimSpace(e.ID) == "" {
				return fmt.Errorf("%s: id is empty", ewhere)
			}
			if seenEntry[e.ID] {
				return fmt.Errorf("%s: duplicate id %q", ewhere, e.ID)
			}
			seenEntry[e.ID] = true
			if err := validateEntry(e); err != nil {
				return fmt.Errorf("%s: %w", ewhere, err)
			}
			pair := e.ServerID + "\x00" + e.VlessUserID
			if seenPair[pair] {
				return fmt.Errorf("%s: the same account is attached twice", ewhere)
			}
			seenPair[pair] = true
		}
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	s.list = doc.Subscribers
	// Normalise on the way in, so a hand-edited lowercase token still resolves.
	for i := range s.list {
		s.list[i].Token = strings.ToUpper(s.list[i].Token)
	}
	s.reindexLocked()
	s.stampLoadedLocked()
	return nil
}

// reindexLocked rebuilds both indexes from the list. Caller holds the lock.
func (s *Subscribers) reindexLocked() {
	s.byID = make(map[string]int, len(s.list))
	s.byToken = make(map[[32]byte]string, len(s.list))
	for i := range s.list {
		s.byID[s.list[i].ID] = i
		s.byToken[sha256.Sum256([]byte(s.list[i].Token))] = s.list[i].ID
	}
}

func (s *Subscribers) stampLoadedLocked() {
	if fi, err := os.Stat(s.path); err == nil {
		s.loadedSize, s.loadedModTime = fi.Size(), fi.ModTime()
	} else {
		s.loadedSize, s.loadedModTime = 0, time.Time{}
	}
}

// Path returns the backing file.
func (s *Subscribers) Path() string { return s.path }

// Writable reports whether this handle may mutate the file.
func (s *Subscribers) Writable() bool { return s.writable }

// Count is the number of subscribers.
func (s *Subscribers) Count() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return len(s.list)
}

// List returns a deep copy, sorted by name so the operator's list does not reorder
// itself on every write.
func (s *Subscribers) List() []Subscriber {
	s.mu.RLock()
	defer s.mu.RUnlock()
	out := make([]Subscriber, 0, len(s.list))
	for i := range s.list {
		out = append(out, s.list[i].clone())
	}
	slices.SortFunc(out, func(a, b Subscriber) int {
		if c := strings.Compare(strings.ToLower(a.Name), strings.ToLower(b.Name)); c != 0 {
			return c
		}
		return strings.Compare(a.ID, b.ID)
	})
	return out
}

// Get finds a subscriber by id.
func (s *Subscribers) Get(id string) (*Subscriber, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	i, ok := s.byID[id]
	if !ok {
		return nil, fmt.Errorf("subscriber %q: %w", id, ErrNotFound)
	}
	sub := s.list[i].clone()
	return &sub, nil
}

// GetByToken resolves a share token.
//
// The index is keyed by a digest even though the token is stored in the clear, and that
// is the timing answer: this hashes the presented token and probes a map, the identical
// construction session.Table uses, where distinguishing entries by timing would require
// finding a 256-bit preimage first.
//
// What must never replace it is a linear scan comparing s.list[i].Token == token. That is
// a byte-at-a-time comparison against a live secret and leaks a prefix. If a scan ever
// becomes unavoidable it has to go through subtle.ConstantTimeCompare; the map makes the
// question moot.
func (s *Subscribers) GetByToken(token string) (*Subscriber, error) {
	// Empty is never a hit. sha256("") is a perfectly good map key, and without this a
	// record whose token somehow failed to save would answer every anonymous request.
	if token == "" {
		return nil, ErrNotFound
	}
	// Crockford is canonically uppercase, and a link that survives a messenger
	// lowercasing it is worth one line. Full Crockford folding (I→1, O→0) is not done:
	// links are copied rather than retyped, and a normaliser that has to stay in exact
	// lockstep with the encoder is a way to end up with two spellings of one token.
	token = strings.ToUpper(strings.TrimSpace(token))
	if validateShareToken(token) != nil {
		// Shape-check before the probe: it means a megabyte of garbage in a path segment
		// costs a length comparison rather than a hash.
		return nil, ErrNotFound
	}
	sum := sha256.Sum256([]byte(token))

	s.mu.RLock()
	defer s.mu.RUnlock()
	id, ok := s.byToken[sum]
	if !ok {
		return nil, ErrNotFound
	}
	sub := s.list[s.byID[id]].clone()
	return &sub, nil
}

// Create adds a subscriber and mints its share token.
func (s *Subscribers) Create(name, note string, now time.Time) (*Subscriber, error) {
	if !s.writable {
		return nil, ErrReadOnly
	}
	name = strings.TrimSpace(name)
	if err := validateSubscriberName(name); err != nil {
		return nil, err
	}
	if len(note) > maxSubscriberNoteLen {
		return nil, fmt.Errorf("%w: note is longer than %d characters", ErrInvalid, maxSubscriberNoteLen)
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	id, err := s.freshIDLocked()
	if err != nil {
		return nil, err
	}
	token, err := s.freshTokenLocked()
	if err != nil {
		return nil, err
	}

	at := now.UTC().Truncate(time.Second)
	sub := Subscriber{
		ID:        id,
		Name:      name,
		Note:      note,
		Token:     token,
		Entries:   []SubscriberEntry{},
		CreatedAt: at,
		UpdatedAt: at,
	}
	s.list = append(s.list, sub)
	if err := s.commitLocked(); err != nil {
		s.list = s.list[:len(s.list)-1]
		s.reindexLocked()
		return nil, err
	}
	out := sub.clone()
	return &out, nil
}

// Update applies a patch. Nothing here can reach Token or ID.
func (s *Subscribers) Update(id string, upd SubscriberUpdate, now time.Time) (*Subscriber, error) {
	return s.mutate(id, now, func(sub *Subscriber) error {
		if upd.Name != nil {
			name := strings.TrimSpace(*upd.Name)
			if err := validateSubscriberName(name); err != nil {
				return err
			}
			sub.Name = name
		}
		if upd.Note != nil {
			if len(*upd.Note) > maxSubscriberNoteLen {
				return fmt.Errorf("%w: note is longer than %d characters", ErrInvalid, maxSubscriberNoteLen)
			}
			sub.Note = *upd.Note
		}
		if upd.Disabled != nil {
			sub.Disabled = *upd.Disabled
		}
		return nil
	})
}

// Delete removes a subscriber, and with it their share link.
func (s *Subscribers) Delete(id string) error {
	if !s.writable {
		return ErrReadOnly
	}
	s.mu.Lock()
	defer s.mu.Unlock()

	i, ok := s.byID[id]
	if !ok {
		return fmt.Errorf("subscriber %q: %w", id, ErrNotFound)
	}
	removed := s.list[i]
	s.list = slices.Delete(s.list, i, i+1)
	if err := s.commitLocked(); err != nil {
		s.list = slices.Insert(s.list, i, removed)
		s.reindexLocked()
		return err
	}
	return nil
}

// Attach adds an account reference.
func (s *Subscribers) Attach(id string, e NewEntry, now time.Time) (*Subscriber, error) {
	entry := SubscriberEntry{
		ServerID:    strings.TrimSpace(e.ServerID),
		VlessUserID: strings.TrimSpace(e.VlessUserID),
		Label:       strings.TrimSpace(e.Label),
		AddedAt:     now.UTC().Truncate(time.Second),
	}
	if err := validateEntry(entry); err != nil {
		return nil, err
	}
	return s.mutate(id, now, func(sub *Subscriber) error {
		if len(sub.Entries) >= MaxEntriesPerSubscriber {
			return fmt.Errorf("%w: a subscriber may hold at most %d accounts", ErrInvalid, MaxEntriesPerSubscriber)
		}
		for _, existing := range sub.Entries {
			if existing.ServerID == entry.ServerID && existing.VlessUserID == entry.VlessUserID {
				return fmt.Errorf("that account is already attached to this subscriber: %w", ErrConflict)
			}
		}
		eid, err := freshEntryID(sub.Entries)
		if err != nil {
			return err
		}
		entry.ID = eid
		sub.Entries = append(sub.Entries, entry)
		return nil
	})
}

// UpdateEntry relabels an attachment. The references themselves are immutable — moving
// an entry to a different account is a detach and an attach, which is honest about the
// fact that it is a different account.
func (s *Subscribers) UpdateEntry(id, entryID string, label string, now time.Time) (*Subscriber, error) {
	label = strings.TrimSpace(label)
	if len(label) > maxEntryLabelLen {
		return nil, fmt.Errorf("%w: label is longer than %d characters", ErrInvalid, maxEntryLabelLen)
	}
	return s.mutate(id, now, func(sub *Subscriber) error {
		for i := range sub.Entries {
			if sub.Entries[i].ID == entryID {
				sub.Entries[i].Label = label
				return nil
			}
		}
		return fmt.Errorf("entry %q: %w", entryID, ErrNotFound)
	})
}

// Detach removes an account reference. The account on the node is untouched.
func (s *Subscribers) Detach(id, entryID string, now time.Time) (*Subscriber, error) {
	return s.mutate(id, now, func(sub *Subscriber) error {
		i := slices.IndexFunc(sub.Entries, func(e SubscriberEntry) bool { return e.ID == entryID })
		if i < 0 {
			return fmt.Errorf("entry %q: %w", entryID, ErrNotFound)
		}
		sub.Entries = slices.Delete(sub.Entries, i, i+1)
		return nil
	})
}

// mutate applies fn to a copy, and swaps it in only if both fn and the save succeed, so
// a rejected edit and a failed write leave memory exactly as it was.
func (s *Subscribers) mutate(id string, now time.Time, fn func(*Subscriber) error) (*Subscriber, error) {
	if !s.writable {
		return nil, ErrReadOnly
	}
	s.mu.Lock()
	defer s.mu.Unlock()

	i, ok := s.byID[id]
	if !ok {
		return nil, fmt.Errorf("subscriber %q: %w", id, ErrNotFound)
	}
	before := s.list[i]
	working := before.clone()
	if err := fn(&working); err != nil {
		return nil, err
	}
	working.UpdatedAt = now.UTC().Truncate(time.Second)

	s.list[i] = working
	if err := s.commitLocked(); err != nil {
		s.list[i] = before
		s.reindexLocked()
		return nil, err
	}
	out := working.clone()
	return &out, nil
}

// commitLocked reindexes and writes. Caller holds the lock.
func (s *Subscribers) commitLocked() error {
	s.reindexLocked()
	return s.saveLocked()
}

// saveLocked rewrites the file, refusing to clobber an edit made underneath us.
//
// admins.json solves the two-writer problem by having exactly one writer — the CLI — and
// a daemon that stats the file and re-reads it. That shape does not transfer here,
// because here the *daemon* is the writer and holds the authoritative list in memory
// between requests. A second writer would not merely race: the daemon's next save
// rewrites the whole file from memory, and the outside change vanishes with no error
// anywhere.
//
// So rather than reconcile, refuse. If size or mtime has moved since we last read or
// wrote, somebody edited the file; say so and change nothing. The operator restarts the
// panel, which re-reads their edit. Losing a mutation with a loud message beats losing an
// edit silently.
func (s *Subscribers) saveLocked() error {
	if fi, err := os.Stat(s.path); err == nil {
		if fi.Size() != s.loadedSize || !fi.ModTime().Equal(s.loadedModTime) {
			return fmt.Errorf("%s changed on disk since this process read it; "+
				"restart the panel to pick that edit up (nothing was written)", s.path)
		}
	}
	if err := writeJSONAtomic(s.path, subscribersDoc{Version: jsonVersion, Subscribers: s.list}); err != nil {
		return err
	}
	s.stampLoadedLocked()
	return nil
}

// freshIDLocked mints an unused subscriber id. Caller holds the lock.
func (s *Subscribers) freshIDLocked() (string, error) {
	for range 4 {
		id, err := randomID()
		if err != nil {
			return "", err
		}
		if _, taken := s.byID[id]; !taken {
			return id, nil
		}
	}
	return "", errors.New("could not mint a unique subscriber id")
}

// freshTokenLocked mints an unused share token. Caller holds the lock.
//
// A collision at 160 bits will not happen; the retry is here because the consequence —
// two subscribers sharing a link — is a disclosure bug rather than a merely confusing
// one, and a loop is cheaper than the argument for leaving it out.
func (s *Subscribers) freshTokenLocked() (string, error) {
	for range 4 {
		token, err := newShareToken()
		if err != nil {
			return "", err
		}
		if _, taken := s.byToken[sha256.Sum256([]byte(token))]; !taken {
			return token, nil
		}
	}
	return "", errors.New("could not mint a unique share token")
}

func freshEntryID(existing []SubscriberEntry) (string, error) {
	for range 4 {
		id, err := randomID()
		if err != nil {
			return "", err
		}
		if !slices.ContainsFunc(existing, func(e SubscriberEntry) bool { return e.ID == id }) {
			return id, nil
		}
	}
	return "", errors.New("could not mint a unique entry id")
}

func newShareToken() (string, error) {
	b := make([]byte, shareTokenBytes)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("generate share token: %w", err)
	}
	return crockford.EncodeToString(b), nil
}

// randomID mints a short lowercase handle, e.g. "k3m9qp2v".
//
// Crockford's alphabet even though this is not a credential: it omits I, L, O and U, so
// an id read off a screen and typed back in cannot be mangled by the usual confusions.
// Lowercased on the way out because it lives in a URL bar next to other lowercase path
// segments, and a shouting id there looks like a mistake.
func randomID() (string, error) {
	b := make([]byte, idBytes)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("generate id: %w", err)
	}
	return strings.ToLower(crockford.EncodeToString(b)), nil
}

// TokenFingerprint is the eight hex characters that stand in for a share token in logs.
//
// An operator can derive the same value from the token they hold, so it answers "did
// Ivan's link reach us?" and "is somebody hammering one dead link?" while being useless
// to whoever reads the log later. Same idea as HashFingerprint.
func TokenFingerprint(token string) string {
	sum := sha256.Sum256([]byte(strings.ToUpper(strings.TrimSpace(token))))
	return fmt.Sprintf("%x", sum[:4])
}

func validateSubscriberName(name string) error {
	name = strings.TrimSpace(name)
	if name == "" {
		return fmt.Errorf("%w: name is required", ErrInvalid)
	}
	if len(name) > maxSubscriberNameLen {
		return fmt.Errorf("%w: name is longer than %d characters", ErrInvalid, maxSubscriberNameLen)
	}
	for _, r := range name {
		if r < ' ' || r == 0x7f {
			return fmt.Errorf("%w: name must not contain control characters", ErrInvalid)
		}
	}
	return nil
}

func validateShareToken(token string) error {
	if len(token) < minShareTokenLen {
		return fmt.Errorf("%w: token is shorter than %d characters, which is not enough to be unguessable",
			ErrInvalid, minShareTokenLen)
	}
	if len(token) > maxShareTokenLen {
		return fmt.Errorf("%w: token is longer than %d characters", ErrInvalid, maxShareTokenLen)
	}
	if !isCrockford(token) {
		return fmt.Errorf("%w: token contains characters outside the share-token alphabet", ErrInvalid)
	}
	return nil
}

func validateEntry(e SubscriberEntry) error {
	if e.ServerID == "" {
		return fmt.Errorf("%w: server_id is required", ErrInvalid)
	}
	if e.VlessUserID == "" {
		return fmt.Errorf("%w: vless_user_id is required", ErrInvalid)
	}
	if len(e.ServerID) > 64 {
		return fmt.Errorf("%w: server_id is longer than 64 characters", ErrInvalid)
	}
	if len(e.VlessUserID) > maxVlessUserIDLen {
		return fmt.Errorf("%w: vless_user_id is longer than %d characters", ErrInvalid, maxVlessUserIDLen)
	}
	if len(e.Label) > maxEntryLabelLen {
		return fmt.Errorf("%w: label is longer than %d characters", ErrInvalid, maxEntryLabelLen)
	}
	// No slash and nothing unprintable: both ids are interpolated into an upstream URL
	// path, and a slash there would silently change which endpoint we called.
	for _, field := range [...]string{e.ServerID, e.VlessUserID} {
		for _, r := range field {
			if r <= ' ' || r == 0x7f || r == '/' || r == '?' || r == '#' {
				return fmt.Errorf("%w: ids must not contain spaces, slashes or control characters", ErrInvalid)
			}
		}
	}
	for _, r := range e.Label {
		if r < ' ' || r == 0x7f {
			return fmt.Errorf("%w: label must not contain control characters", ErrInvalid)
		}
	}
	return nil
}

func isCrockford(s string) bool {
	for _, r := range s {
		if strings.IndexRune("0123456789ABCDEFGHJKMNPQRSTVWXYZ", r) < 0 {
			return false
		}
	}
	return true
}
